In [8]:
import numpy as np

In [9]:
numbers = np.array([2, 3, 5, 7, 11])

In [10]:
type(numbers)

numpy.ndarray

In [12]:
numbers

array([ 2,  3,  5,  7, 11])

In [13]:
np.array([[1, 2, 3], [4, 5, 6]])

array([[1, 2, 3],
       [4, 5, 6]])

In [14]:
import numpy as np

In [15]:
integers = np.array([[1, 2, 3], [4, 5, 6]])

In [16]:
integers

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
floats = np.array([0.0, 0.1, 0.2, 0.3, 0.4])

In [18]:
floats

array([0. , 0.1, 0.2, 0.3, 0.4])

In [19]:
integers.dtype

dtype('int64')

In [20]:
floats.dtype

dtype('float64')

In [21]:
integers.ndim

2

In [22]:
floats.ndim

1

In [23]:
integers.shape

(2, 3)

In [24]:
floats.shape

(5,)

In [25]:
integers.size

6

In [27]:
integers.itemsize

8

In [28]:
floats.size

5

In [29]:
floats.itemsize

8

In [30]:
for row in integers:
    for column in row:
        print(column, end='  ')
    print()

1  2  3  
4  5  6  


In [31]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [32]:
np.ones((2, 4), dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [33]:
np.full((3, 5), 13)

array([[13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13],
       [13, 13, 13, 13, 13]])

In [35]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [36]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [37]:
np.arange(10, 1, -2)

array([10,  8,  6,  4,  2])

In [38]:
np.arange(1, 100001).reshape(4, 25000)

array([[     1,      2,      3, ...,  24998,  24999,  25000],
       [ 25001,  25002,  25003, ...,  49998,  49999,  50000],
       [ 50001,  50002,  50003, ...,  74998,  74999,  75000],
       [ 75001,  75002,  75003, ...,  99998,  99999, 100000]])

In [39]:
np.arange(1, 100001).reshape(100, 1000)

array([[     1,      2,      3, ...,    998,    999,   1000],
       [  1001,   1002,   1003, ...,   1998,   1999,   2000],
       [  2001,   2002,   2003, ...,   2998,   2999,   3000],
       ...,
       [ 97001,  97002,  97003, ...,  97998,  97999,  98000],
       [ 98001,  98002,  98003, ...,  98998,  98999,  99000],
       [ 99001,  99002,  99003, ...,  99998,  99999, 100000]])

In [44]:
import random

In [49]:
import numpy as np

In [50]:
grades = np.array([[87, 96, 70], [100, 87, 90],
                   [97, 77, 90], [100, 81, 82]])

In [51]:
grades

array([[ 87,  96,  70],
       [100,  87,  90],
       [ 97,  77,  90],
       [100,  81,  82]])

In [58]:
grades.sum()

1057

In [59]:
grades.min()

70